### ISSUE TITLE
Support inbox folder

### ISSUE THREAD

**Issue by Zachatoo** [Zachatoo/obsidian-inbox#9]
I personally don't have a need for this, but I think it could be an interesting idea, feel free to upvote or comment your thoughts on this. Happy to add this or accept contributions for this feature if it's something people want.

---

Instead of checking for updates to an inbox note, there could be a setting to check for updates to an inbox folder.

For example, if a new note is added to a folder, then on startup, show a notification to let the user know there are new notes to process.

Could also check to see if there's any notes in the inbox folder.

Checking to see if a note in the inbox folder was modified probably doesn't make sense for this use case.

**Comment by JoelAnderson-UU** [comment]
I actually think this would be really useful!  Here's my use case:  I often write quick notes in the Drafts app on Mac or iOS, and then I have an "Action" in Drafts that sends the text as a MD file to a inbox folder in Obsidian (and deletes the file in Drafts).  It would be great to get an alert about new files in that folder.

**Comment by Zachatoo** [comment]
Released in version 2.0.1. If any issues are found, please report in a new GitHub issue. Thank you!

**Comment by autonomygaps** [comment]
Awesome!  Really useful for helping me to keep my inbox backlog from getting clogged up!

As [Andy Matuschak](https://andymatuschak.org/) says…
> Inboxes only “work” if you trust how they’re drained. From a queue-processing perspective: the departure rate must be above some threshold. Inbox Zero “works” by aggressively increasing that rate (via defer, delegate, drop)—blunt, but ensures that departure rate > arrival rate.
https://twitter.com/andy_matuschak/status/1367912185100267526
